name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 EC2 접속
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/boot-demo
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 80 || true
            sudo nohup java -jar build/libs/*SNAPSHOP.jar > ./output.log 2>&1